---
title: "sakura"
author: "Yuriko Schumacher"
date: "3/11/2021"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
library(weathermetrics)
library(lubridate)

```


```{r}
mean.temp.raw <- read_excel("data/raw data/759Temp7.xls", na = "-999.9")

mean.temp <- mean.temp.raw[-c(1:14), ] %>%
  select(year = `759Temp7.xls`,
         tempC = ...2) 

year <- c(2011, 2012, 2013, 2014, 2015)
tempC <- c(6.8, 8.3, 9.7, 9.0, 9.4)
rows_to_add <- data.frame(year, tempC)

mean.temp.added <- rbind(mean.temp[-1211, ], rows_to_add)

mean.temp.final <- mean.temp.added %>% 
  mutate(
    year = as.numeric(year),
    tempC = as.numeric(tempC),
    tempF = celsius.to.fahrenheit(tempC, round = 2))


sakura <- cbind(cb.cleaned, mean.temp.final) %>% 
  select(-8)

# write_csv(sakura, "data/sakura.csv")
```

```{r}
full.bloom.raw <- read_csv("data/sakura_full_bloom_dates.csv")
first.bloom.raw <- read_csv("data/sakura_first_bloom_dates.csv")

# from 1953 to 2020
full.bloom.gathered <- full.bloom.raw %>% 
  select(-`30 Year Average 1981-2010`, -Notes) %>% 
  gather(key = "year", value = "date", "1953":"2020") %>% 
  rename(location = `Site Name`,
         now.observed = `Currently Being Observed`) %>% 
  filter(location == "Kyoto") %>% 
  select(-now.observed, -location)

first.bloom.gathered <- first.bloom.raw %>% 
  select(-`30 Year Average 1981-2010`, -Notes) %>% 
  gather(key = "year", value = "date", "1953":"2020") %>% 
  rename(location = `Site Name`,
         now.observed = `Currently Being Observed`) %>% 
  filter(location == "Kyoto") %>% 
  select(-now.observed, -location)

# add 2021 data
kyoto_first.2021 <- c("2021", "2021-03-16")
kyoto_full.2021 <- c("2021", "2021-03-26")

full.bloom.1953 <- rbind(full.bloom.gathered, kyoto_full.2021) %>% 
  mutate(
    date = as.Date(date, format = "%Y-%m-%d"),
    date.jan1 = as.Date(paste(year, "-01-01", sep = ""), format = "%Y-%m-%d"),
    full_doy = as.numeric(date - date.jan1)) %>% 
  select(date, year, full_doy)

first.bloom.1953 <- rbind(first.bloom.gathered, kyoto_first.2021) %>% 
  mutate(
    date = as.Date(date, format = "%Y-%m-%d"),
    date.jan1 = as.Date(paste(year, "-01-01", sep = ""), format = "%Y-%m-%d"),
    first_doy = as.numeric(date - date.jan1)) %>% 
  select(year, first_doy)

bloom.1953 <- cbind(first.bloom.1953, full.bloom.1953) %>% 
  select(-3)

# from 1881 to 1952
cb.1881.1952 <- cb.cleaned %>% 
  rename(full_doy = date_doy) %>% 
  select(year, full_doy) %>% 
  filter(year >= 1881 & year <= 1952) %>% 
  mutate(first_doy = "NA")

# bind data
cb.full <- rbind(cb.1881.1952, bloom.1953)

write_csv(cb.full, "data/kyoto_1881-2021.csv")

# kyoto temperature data
kyoto.temp <- read_csv("data/kyoto-temperature.csv") %>% 
  mutate(year = ceiling(row_number() / 15) + 1880,
         interval = row_number() %% 15) %>% 
  mutate(interval = ifelse(interval == 0, 15, interval)) %>% 
  select(-date_from)

seasons <- c("early_Nov", "mid_Nov", "late_Nov", "early_Dec", "mid_Dec",
         "late_Dec", "early_Jan", "mid_Jan", "late_Jan", "early_Feb",
         "mid_Feb", "late_Feb", "early_Mar", "mid_Mar", "late_Mar")

seasonal <- kyoto.temp %>% 
  mutate(month = seasons[as.numeric(interval)]) %>% 
  select(-interval)

write_csv(seasonal, "data/seasonal-temp.csv")


# monthly temperature
monthly <- read_csv("data/kyoto-monthly-temperature.csv") %>% 
  mutate(year = ceiling(row_number() / 5) + 1880,
         interval = row_number() %% 5) %>% 
  mutate(interval = ifelse(interval == 0, 5, interval)) %>% 
  select(-year_month)

months = c("avg_Nov", "avg_Dec", "avg_Jan", "avg_Feb", "avg_Mar")

monthly.final = monthly %>% 
  mutate(month = months[as.numeric(interval)]) %>% 
  select(-interval)

write_csv(monthly.final, "data/monthly-temp.csv")

# bind data
cb.final <- cbind(cb.full, temp.spread, monthly.spread) %>% 
  select(-4, -20)

# write_csv(cb.final, "data/temp_merged.csv")
```

```{r}
cb.raw <- read_excel("data/raw data/KyotoFullFlower7.xls")

cb.cleaned <- cb.raw[-c(1:25), ] %>% 
  select(year = `Full-flowering dates of Japanese cherry (Prunus jamasakura) at Kyoto, Japan. (Latest version, Jun. 12, 2012)`,
         date_doy = ...2,
         date = ...3,
         source_type = ...5,
         source = ...6) %>% 
  mutate(year = as.numeric(year), 
         date_doy = as.numeric(date_doy),
         month = as.numeric(str_sub(date, end = 1)),
         day = as.numeric(str_sub(date, start = 2)))

cb <- cb.cleaned %>% 
  mutate(month = ifelse(month == 3, "Mar", ifelse(month == 4, "Apr", "May"))) %>% 
  select(year, date_doy, month, day, source_type, source)

cb <- cb[-c(1153:1215),]

full.bloom.raw <- read_csv("data/sakura_full_bloom_dates.csv")

# from 1953 to 2020
full.bloom.gathered <- full.bloom.raw %>% 
  select(-`30 Year Average 1981-2010`, -Notes) %>% 
  gather(key = "year", value = "date", "1953":"2020") %>% 
  rename(location = `Site Name`,
         now.observed = `Currently Being Observed`) %>% 
  filter(location == "Kyoto") %>% 
  select(-now.observed, -location)

kyoto_full.2021 <- c("2021", "2021-03-26")

full <- rbind(full.bloom.gathered, kyoto_full.2021) %>% 
  mutate(
    date = as.Date(date, format = "%Y-%m-%d"),
    date.jan1 = as.Date(paste(year, "-01-01", sep = ""), format = "%Y-%m-%d"),
    full_doy = as.numeric(date - date.jan1)) %>% 
  select(year, full_doy, date) %>% 
  rename(date_doy = full_doy) %>% 
  mutate(month = month(date, label = TRUE, abbr = TRUE),
         day = day(date)) %>% 
  select(-date)

full$source_type <- 0
full$source <- "Japan Meteorological Agency"

sakura_new <- rbind(cb, full)

# add temperature data
kyoto.march.mean.temp <- read_csv("data/kyoto-march-mean-temperature.csv") %>% 
  mutate(year = str_sub(year, end = 4)) %>% 
  rename(tempC = avg_temp)

mean.temp.raw <- read_excel("data/raw data/759Temp7.xls", na = "-999.9")

mean.temp <- mean.temp.raw[-c(1:14), ] %>%
  select(year = `759Temp7.xls`,
         tempC = ...2) 

mean.temp <- mean.temp[-c(1081:1211), ]

temp <- rbind(mean.temp, kyoto.march.mean.temp) %>% 
    mutate(
    year = as.numeric(year),
    tempC = as.numeric(tempC),
    tempF = celsius.to.fahrenheit(tempC, round = 2))

library(zoo)

sakura_new <- cbind(sakura_new, temp) 
sakura_new <- sakura_new %>% 
  select(-7) 
sakura_new <- sakura_new %>% 
  mutate(doy_100yr = rollmean(date_doy, k = 100, fill = date_doy, align = "right", na.rm = TRUE))

# write_csv(sakura_new, "data/sakura.csv") 
```

```{r}
sakura1500_1900 <- sakura_new %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year >= 1500 & year <= 1900) 

summary(sakura1500_1900)

sakura_ancient <- sakura_new %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year < 1900) %>% 
  group_by(date_doy) %>% 
  summarize(Count = n()) %>% 
  mutate(time = "ancient")%>% 
  filter(!is.na(date_doy))

sakura_modern <- sakura_new %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year >= 1900) %>% 
  group_by(date_doy) %>% 
  summarize(Count = n()) %>% 
  mutate(time = "modern")%>% 
  filter(!is.na(date_doy))

sakura_modern %>% 
  summarize(median = median(date_doy))

sakura_new %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year >= 1900)  %>% 
  filter(date_doy < 105)

sakura_paired <- rbind(sakura_ancient, sakura_modern) %>% 
  mutate(date_doy = as.numeric(date_doy)) %>% 
  filter(!is.na(date_doy))

ggplot(data = sakura_ancient,
       mapping = aes(x = date_doy, y = time, fill = Count)) + 
  geom_tile(color = "#3e3d3d", size = 0.3) +
  scale_fill_gradient(high = "#F880AA", low = "#FFF7F3") +
  coord_equal() +
  labs(x = "Days after Jan. 1", y = "") +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank()) 

ggplot(data = sakura_modern,
       mapping = aes(x = date_doy, y = time, fill = Count)) + 
  geom_tile(color = "#3e3d3d", size = 0.3) +
  scale_fill_gradient(high = "#F880AA", low = "#FFF7F3") +
  coord_equal() +
  labs(x = "Days after Jan. 1", y = "") +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank()) 

ggplot(data = sakura_paired,
       mapping = aes(x = date_doy, y = time, fill = Count)) + 
  geom_tile(color = "#3e3d3d", size = 0.3) +
  scale_fill_gradient(high = "#F880AA", low = "#FFF7F3") +
  coord_equal() +
  labs(x = "Days after Jan. 1", y = "") +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank()) 

install.packages("svglite")
library(svglite)

ggsave("ancient.svg")

ggplot(data = sakura_paired, mapping = aes(x = date_doy)) +
  geom_histogram(binwidth = 4) +
  facet_wrap(vars(time))
```

